export const DEFAULT_ACTION = "DEFAULT_ACTION";
export const DEFAULT_ACTION_HANDLED = "DEFAULT_ACTION_HANDLED";

export const PARTNER_CREATE_PARTNER = "PARTNER_CREATE_PARTNER";
export const PARTNER_UPDATE_PARTNER = "PARTNER_UPDATE_PARTNER";
export const PARTNER_DELETE_PARTNER = "PARTNER_DELETE_PARTNER";



